regro/regolith

- news/case_insensitive_fuzzy.rst
- regolith/builders/preslistbuilder.py
- regolith/tools.py
- tests/test_tools.py
I wanted to try an option where we don't have to worry about capitalization in ``fuzzy_retrieval()``.  This will make it easier building aka lists, but could lead to more false-positives in the retrieval.  Anyway, I added it as an option with current behavior (case sensitive) as default so it should be safe.   I also mistakenly committed changes to ``preslistbuilder`` which are not strictly part of this PR, but....
@scopatz @CJ-Wright I think this is ready for review
> case insensitive option added to fuzzy_retrieval

- news/postdocadbuilder.rst
- regolith/builder.py
- regolith/builders/postdocadbuilder.py
- regolith/templates/postdocad.tex
Hi @scopatz @CJ-Wright 
I don't want this pulled in because it is rather specific to MY needs, but I am making a PR to initiate some discussion about this issue....
I want to build builders with templates that are specific to my needs.  Perhaps others could adapt them for themselves, or not, I don't really care.  What I think this calls for is something like a local template database for these things, and perhaps local builders, I am not sure.
For now I just put this into a branch so I can build it locally, but to avoid it getting too complicated for me with hundreds of bespoke branches for this and that builder, I wonder if we could discuss what would be a good way to handle this more generally.
Not sure if I am being clear but....let me know your thoughts.
> post-doc ad builder

- regolith/schemas.py
@scopatz @CJ-Wright this is a very small one.  I noticed street was defined twice in the institutions schema.
> FIX: removing duplicate street in institutions schema

- news/schemas.rst
- regolith/main.py
- regolith/tools.py
- tests/test_tools.py
I am Songsheng Tao in Billinge group. I would like to recommend that we use the recursively merging of two nested dictionary to update the schemas instead of iterating the first two levels of keys. It will provide the user the freedom to add their own yaml files to db and add their own properties for the entries in yaml files.
> Use recursively merging to update the default schemas according to user schemas

- news/bug_handle_database_when_no_rc_remote.rst
- regolith/database.xsh
@scopatz This is a bug that came up only with ``regolith grade``, but I don't have any ``rc.remote`` attribute set and databases weren't loading (working fine for regolith build, validate, etc. for some reason).  A quick @CJ-Wright hack fix was to simply comment out these lines in the xonsh file.
A fix could be for me to set rc.remote somehow, but I feel that this may be a bug or undesirable behavior so putting in a PR to discuss and possibly fix it.
> get databases to build when I don't have an rc.remote set

- news/publist_by_date_and_grant.rst
- regolith/builders/publistbuilder.py
- regolith/dates.py
- regolith/main.py
- regolith/schemas.py
- regolith/templates/publist.tex
- tests/outputs/publist/scopatz.tex
- tests/outputs/resume/scopatz.tex
This is the first use of the date and time args that were added some time ago.  This makes it possible to build a publication list for a limited date range and for a specific grant.
> Publist by daterange grant

- docs/broker.rst
- regolith/broker.py
- regolith/builders/figurebuilder.py
- regolith/storage.py
- tests/bootstrap_builders.py
- tests/test_broker.py
- tests/test_builders.py
The broker was misbehaving when run from the command line and utilizing the filesystem. The path coming up for the storage would always be relative when retrieved by the storageclient, and this would make the figurebuilder unusable. I have now tested this fix on both windows and linux and seen that it works. I have also run_tests.py and seen that it works.
> Local broker fix

- docs/broker.rst
- regolith/builders/basebuilder.py
- regolith/builders/figurebuilder.py
- regolith/storage.py
A few changes were necessary to get figure builder working on windows. This involved the change to the storage module that I removed from the broker PR, as well as a change to the pdf generating section of the figure builder. That last change was necessary to get the figure builder working in general (it was making files with double .tex at the end). This branch passes all of the tests.
I should be ready to showcase this at the group meeting.
> Figure Builder Windows

- news/use_mongo.rst
- regolith/commands.py
- regolith/database.xsh
- regolith/main.py
- regolith/mongoclient.py
- tests/conftest.py
- tests/test_builders.py
- tests/test_commands.py
Hi @sbillinge . I make the regolith work for the cloud based mognodb (also local host mognodb). I test it by building the beamplan from the cloud based rg-db-group in my cloud. Ready for review.
I deprecate the one functionality of the mongoclient in regolith: start the mongo server and close it after the run is finished. The motivation is that (1) starting and closing server take time (2) usually the server will always run in the backend and we don't really need to open and close it every time we run a regolith command (3) if we encounter some error in the run, the server will not be closed and user usually doesn't notice that and when the user tries to run again, it will produce error because regolith will try to start a server that is already running.
> DEV: make regolith work on could based mongodb

- tests/test_builders.py
Hi @sbillinge Please merge this PR. I realized that my automatically starting client functionality only works for osx and linux. I should skip the tests for windows.
> TST: move the mongo test to the test_builder; skip for windows.

- tests/test_builders.py
Hi @sbillinge @scopatz . I thought out a solution to fix the file path issue in test builders. I use the word by word comparison between two strings and ignore the comparison if certain substring is contained. How do you think of it?
> TST: use word by word comparison to fix the file path issue

- regolith/helpers/f_todohelper.py
- regolith/helpers/l_todohelper.py
- regolith/helpers/u_todohelper.py
- tests/outputs/f_todo/people.yaml
- tests/test_helpers.py
Hi @sbillinge! I haven't sync printed lists in l_todo, f_todo and u_todo. I will do it soon after we decide which way to choose (please see comments in issue#572). 
In this PR, there are several things:
1. delete begin-date and end-date in u_todo. 
2. add flag --end_date in f_todo, cuz when we use f_todo to mark a task as finished, I think it's better to set end_date as today automatically, or specify an end_date.
3. add an algorithm in l_todo to sort tasks. I tried:  order = importance + 1/[1 + exp(|days to due date|)]. The second part  "1/[1 + exp(|days to due date|)] " ranges from 0 to 0.5. So by using that algorithm, importance 2 will always stay top, importance 1 is at the middle, and 0 is at the bottom. In each importance level, the tasks will be sorted by the absolute value of …
> fix some bugs and add order algorithm in l_todo

- regolith/helpers/a_todohelper.py
- regolith/helpers/f_todohelper.py
- regolith/helpers/l_todohelper.py
- regolith/helpers/u_todohelper.py
- regolith/schemas.py
- regolith/tools.py
- tests/outputs/a_todo/people.yaml
- tests/outputs/f_todo/people.yaml
- tests/outputs/u_todo/people.yaml
- tests/test_helpers.py
Hi @sbillinge 
This PR mainly updates:
1. sorting of finished tasks
2. add -b,  --assigned_by:
if enter -b, then helper lists tasks assigned by the id in user.json, if -b jwzang, then lists tasks assigned by jwzang.
3. add -s,  --stati:
if no -s, then helper lists started tasks, if -s finished, then lists finished tasks, if -s finished started, then lists all tasks.
4. make the shortcuts consistent
I will soon make a separate PR for kv filter after this PR is merged, in case too many codes are changed.
> add assigned_by and update sorting in todolist

- tests/conftest.py
- tests/test_builders.py
Modified the tests such that windows will now run mongodb tests if mongodb is installed, and all computers will now be able to selectively run filesystem tests and skip mongo tests. There will be a printout saying that the mongo tests were skipped, a link to where to install mongo, and a xonsh shell error saying that the mongo commands do not exist if the user has not installed mongodb community edition.
> Mongodb Test on Windows

- news/helper_f_milestone.rst
- regolith/helpers/u_milestonehelper.py
This PR closes #624 
@sbillinge please review and merge.
BTW, how do you want the string argument to be put into `report_summary`? Currently I make it force to be an input, or we can change it to optional.
> ENH: add finish milestone option.

- regolith/mongoclient.py
- tests/conftest.py
Updated the mongo functionality such that it should work without requiring that compass is installed on windows. Next step is to add the missing find_one method to the mongo_client. 
FS and Mongo tests are passing locally for all builders other than html on my windows pc.
> Remote mongo updates

- regolith/builder.py
- regolith/builders/bghtmlbuilder.py
- regolith/templates/bghtmltemplate.html
Hi @sbillinge , I succeeded in passing the Google drive images to the html, and it can appear properly now.
I did some testing, lionmail google drive doesn't work, so we need to use a general gmail's google drive to save figures.
What I don't quite know is how to get values from yaml to the `bghtmlbuilder.py` level. So currently in this PR, I just write the texts and image id in the function to show you it works as you expected.
You can try running `regolith build bghtml` and click at the `html` file and see a figure (the PDFitc home page scrernshot) showing up.
> build bghtml

- regolith/fsclient.py
I just added a DelayedKeyboardInterrupt context manager to fsclient that I copied and pasted from stackoverflow. I put the context manager inside the code for the dump_yaml() function. When I tried to do a keyboard interupt during dumping, it seems to work properly on my end. Can you add the fork as a remote and see if it works for you too?
> WIP Adding keyboard interrupt signal delay to fsclient.py

- news/mongo_validation.rst
- regolith/dates.py
- regolith/helpers/l_abstracthelper.py
- regolith/helpers/l_contactshelper.py
- regolith/helpers/l_generalhelper.py
- regolith/helpers/l_grantshelper.py
- regolith/helpers/l_membershelper.py
- regolith/helpers/l_milestoneshelper.py
- regolith/helpers/l_progressreporthelper.py
- regolith/helpers/l_projectahelper.py
- regolith/helpers/l_todohelper.py
- regolith/helpers/u_milestonehelper.py
- regolith/mongoclient.py
- regolith/tools.py
- setup.py
- tests/conftest.py
- tests/test_client_manager.py
- tests/test_helpers.py
- tests/test_validators.py
I added validation via cerberus schemas prior to upload to mongo, since there is no longer going to be a PR review process. 
In the process of doing this I realized I should test the helpers or I would have no idea if the validation was working. So I added testing on mongo db to every helper and fixed every issue that arose.
If you want eyes on every time someone does something specific, like adding a prum, maybe we can insert an automatic email process that asks you to review a new prum added by person x.
> Client-side Cerberus validation added to inserts and updates

- regolith/helpers/basehelper.py
- tests/test_helpers.py
Solving the issue where helpers make an unneeded empty folder in the _build directory. Fixed a larger issue where helper outputs were not being tested in test_helpers.
> reopening PR for pl_rego_helper_no_folder, closes #751

- regolith/client_manager.py
- regolith/commands.py
- regolith/main.py
- regolith/mongoclient.py
- tests/conftest.py
- tests/test_commands.py
- tests/test_helpers.py
After @sbillinge comment yesterday asking if they should upload their todo list and work on mongo, I realized that I should prioritize the ability to periodically backup mongo to the filesystem. 
This commit allows the user to backup a mongo database with the directory they dedicate for fs-to-mongo porting. They simply go to local and type "regolith mongo-to-fs" into the terminal with the develop banch active. The entirety of the database will be pulled from the dst_url database into their local db folder in the form of json files. 
I've also commented out the running of mongo helper tests, because they seem to be taking a relatively long time. 
All mongo helper tests have been run locally on windows and ubuntu before submitting this PR.
> Mongo to fs backup added

- regolith/builders/internalhtmlbuilder.py
Updated allowed tags in the `doi` field of journal clubs. Now `na` is allowed and will appear as "N/A" in the html. Also, temporary journal article identifiers for arXiv papers are permitted (without being incorrectly cross-referenced through habanero) but will instead appear as simply the arXiv tag in the journal club entries rather than a full citation.
> Fixed issues regarding allowed doi entries and how different tags are handled

- regolith/builders/preslistbuilder.py
Updating docstring to reflect changes in how a group member's ID is converted to the name that will appear in a publication citation as discussed in Issue #645
> Updated in-line documentation to reflect how an author name's is obtained for citation

- .travis.yml
closes #635 
Testing minimal Python specification such that TravisCI always builds with the most recent version of Python3
> Testing minimal Python specification in TravisCI

- setup.py
There is currently one bug, which is that when the shebang line created in the helper_gui entry_point in the packages folder is #!/"usr/bin/env pythonw", instead of #!/usr/bin/env/pythonw.
> WIP allowing helper_gui to be run on mac by editing setup.py

- regolith/client_manager.py
- regolith/database.xsh
Git remotes can now be utilized and chained, which was accidentally broken previously. Tests not added.
Regolith currently has no tests for the git backend. Functionality with the GIT backend broke because the client_manager object was not returning the files that git would need to add before pushing. 
This issue was found via the rg-db-public build failure.
The delay in rg-db-public build failure was likely because building from a git backend repo was failing silently, since the repo was failing to get push rights to the website. These permissions must have recently changed, allowing this to fail loudly.
This has been sorted out logically, but is yet to be tested.
A test could involve creating a public git repository specifically for testing purposes. All that we would need to test (in …
> Fixed Issue with GIT backends

- .travis.yml
- tests/test_validate.py
It seems two of the tests in  `tests/test_validate.py` were using an old syntax for obtaining/validating the output of a `subprocess.run(...)` call through the `xonsh` library
> Fixing CI Bug

- regolith/templates/people.html
I think the change is as simple as this. It is also labeled as .capitalize on the person's page instead of title case, but since it is in a heading font it overwrites the capitalization to make everything capital.
> changed positions on webpage to title case

- setup.py
@sbillinge, this simple single-line deletion should be sufficient to correct the previous issue preventing release of `regolith`.
> Applying fix to successfully release new version of regolith

- regolith/helpers/a_presentationhelper.py
Closes #880 and assigns default behavior for the a_presentation helper --notes option. Default behavior is an empty list. If notes are added, the rc.notes will update the document with a list of strings.  
All tests pass for test_helpers.py as well.
> WIP: Regolith Fix #880 v4

- regolith/helpers/u_milestonehelper.py
- tests/outputs/f_prum/projecta.yaml
- tests/outputs/u_logurl/projecta.yaml
- tests/outputs/u_milestone/projecta.yaml
- tests/test_helpers.py
Removes loops for uuids. this has to be removed because the database is only updated after the code is executed...meaning only the last uuid entered would actually be updated. we do not want to confuse the use, so it is best to add the functionality to update multiple milestones later. success and fail messages have been added and their logic has been changed so that they are printed after a successful update or a failure. test helpers | output files : these were updated to test the the code that update a kickoff meeting and the --finish argument
closes #1009
> u_milestonehelper.py: only one milestone uuid input allowed now.

- news/fix_prop_adder.rst
- regolith/commands.py
- regolith/helper.py
- regolith/helpers/u_milestonehelper.py
- tests/test_helpers.py
Also, change order of command line args in u_milestone for greater ease of use
> invert fast updater logic so only whitelisted updaters use the behavior.

- news/helper_connect.rst
- regolith/helper_connect_main.py
- regolith/main.py
- scripts/helper_connect
- scripts/helper_connect.bat
- setup.py
Can get it to return the version number
> new helper_connection app is now installed and running but not doing anything.

- regolith/builders/beamplanbuilder.py
- regolith/builders/coabuilder.py
- regolith/builders/cpbuilder.py
- regolith/builders/figurebuilder.py
- regolith/builders/formalletterbuilder.py
Leave 2 F401 error in formalletterbu…ilder.py in try statement with import modules.
> Fix issue followed PEP-8 standard 

- regolith/tools.py
I leave E722 for check, which is `do not leave bare except`. However, the code structure is like this:
> Fix import not used and E501 issues 

- README.rst
- doc/source/conf.py
- src/regolith/schemas.json
Merge README.rst and conf.py (safe merge to api)
> README.rst and conf.py update

- .github/workflows/tests-on-pr.yml
Pytest CI passes:
This successfully builds wxPython from sdist like in labpdfproc. Hence, it will take 28 mins to build.
> Configure non-reusable Python 3.11 Test on PR GitHub CI

- .github/workflows/publish-docs-on-release.yml
Closes #https://github.com/regro/regolith/issues/1068 - make github workflow for building docs on merge to main
In our cookiecutting standard, we deploy docs when released., instead of when merged to main as the issue suggests.
> Add build docs .yml on release and by workflow dispatch

- requirements/build.txt
- requirements/conda.txt
- requirements/pip.txt
Closes https://github.com/regro/regolith/issues/1195 - check the package dependencies
> Remove python-dateutil in pip.txt and conda.txt

- news/cookie-news.rst
fix #1214. I added `cookie-news.rst` to the `news/` folder per cookiecutting instruction. Let me know if we need anything else here!
> add news item

- news/finished_todos.rst
- src/regolith/helpers/l_todohelper.py
- src/regolith/tools.py
- tests/test_helpers.py
> fix: todo lister now can list finished task in a better way
