regolith/database.py, regolith/deploy.py
This adds the ability to prefix a URL with `hg+` and use `python-hglib` to interact with it.
=> Adding hg support

regolith/database.py
This fixes a minor hg bug; more fixes incoming in subsequent PRs.
=> Making client status check a bit saner

regolith/storage.py
=> Add hg support for doc storage

regolith/sorters.py
I *think* this is a not-likely-to-fail way of sorting by the first letter of the last name in addition to `position`
=> Add sorting by first letter of last name

docs/api/interactive.rst, regolith/interact.py
=> ENH: add interactive mode

.gitignore, news/TEMPLATE.rst, rever.xsh
=> ENH: add conda forge rever activity

regolith/app.py
If there is a bad entry write it down to disk so that the user can try to salvage it.
=> Save bad entry

news/super.rst, regolith/htmlbuilder.py
=> actually call super

news/cvfix.rst, regolith/cvbuilder.py, regolith/tools.py
=> fixed issue with CVbuilder not filtering grants properly

news/encoding.rst, regolith/fsclient.py
=> FIX: windows encoding problem

news/cl.rst, regolith/classlist.py
=> classlist fixes

news/classlist.rst, regolith/emailer.py, regolith/main.py
=> Class filter bugfix

news/fix_abstract_error.rst, regolith/fsclient.py
https://travis-ci.org/ergs/rg-db-public/jobs/338768761#L1752
=> fix error from abstracts 

docs/commands/index.rst, docs/commands/validate.rst, docs/index.rst, news/validate_cmd.rst, regolith/commands.py, regolith/main.py, regolith/schemas.py
=> ENH: add command for validating dbs

regolith/app.py, regolith/chained_db.py, regolith/templates/collection.html
=> FIX: fix the regolith app (json.dumps is not chain friendly)

news/build_local.rst, regolith/database.py, regolith/fsclient.py, regolith/main.py, regolith/tools.py
=> ENH: allow db loading from local filesystems outside of vc

docs/conf.py
@sbillinge @scopatz ready for review!
=> DOC: autobuild the command docs

regolith/commands.py, tests/conftest.py, tests/test_validate.py
=> FIX: give validate real teeth (previously didn't print errors)

news/test_bootstrap.rst, tests/bootstrap_builders.py
@scopatz @sbillinge ready for review
=> TST: add boostrap code

news/aka_in_groups_schema.rst, regolith/schemas.py
=> added aka to groups

docs/collections/index.rst, docs/commands/index.rst, docs/commands/validate.rst, docs/conf.py, docs/index.rst, news/fix_valid.rst, regolith/commands.py, regolith/main.py, regolith/schemas.py, tests/test_validate.py
institutions, and allowing validate to optionally run on a single
collection
=> make validate better by erroring on bad validation, adding docs for

news/yaml_order.rst, regolith/fsclient.py
=> Make yaml order deterministic

news/preslist_spacing.rst, regolith/builders/preslistbuilder.py, regolith/fsclient.py, regolith/templates/preslist.tex
small fix to preslist formatting
=> Preslist spacing

regolith/templates/preslist.tex
dang, that previous fix didn't fix it, but now with @CJ-Wright 's help we have a fix.  Jinja2 is a sensitive and delicate, and slightly irrational, beast
=> better fix for the suffix spacing

news/phone_address.rst, regolith/templates/cv.tex, regolith/templates/resume.tex, tests/outputs/cv/scopatz.tex, tests/outputs/resume/scopatz.tex
Add phone and address to cv/resume
=> Phone address

news/testing.rst, regolith/builders/reimbursementbuilder.py, regolith/schemas.py, regolith/tools.py
fixes bug that builder couldn't build more than one reimbursement without dying (thanks for the help @CJ-Wright ). 
I had big plans for this PR (to handle grants differently/properly in the reimbursements and to allow for more than one grant) but it was a bigger job than I originally thought and some people need reimbursements so this is just a bug-fix PR now.  I would like it merged if possible and make a new one for that refactor
=> Clean reimb builder

docs/collections/index.rst, docs/conf.py, news/reviewbuilder.rst, regolith/builder.py, regolith/builders/manuscriptreviewbuilder.py, regolith/schemas.py, regolith/templates/refreport_author.txt, regolith/templates/refreport_editor.txt
This is crutch to help simon write better paper reviews.
It needs  a news and it needs a schema update, but @CJ-Wright should be able to use it for his paper review....
=> basic working version of manuscript review builder

news/xonsh_rmtree.rst, tests/conftest.py
closes #243
(I think? @sbillinge, please test this out when you get a chance)
=> use xonsh rmtree

regolith/builders/proposalreviewbuilder.py, regolith/schemas.py
@scopatz Dang, you merged while I was on a flight working on the schemas!  
Thanks so much for doing that.  But now I think it _is_ just about finished.  It now builds proposal reviews for doe and nsf and has been tested in the real-world with a bunch of proposals........
I rebased onto upstream master so this should probably go in easily.
=> Prop rev builder

news/add_from_to_args_to_builder.rst, regolith/builders/preslistbuilder.py, regolith/main.py
closes #249 
At least the date range part of it.  Not sure about the other parts as yet.
=> added cmd line args --from and --to to build command

news/date_range_filter.rst, regolith/tools.py, tests/test_tools.py
If I can give ``since`` and ``before`` date ranges on the command line, I would like to have easy to use helper functions that can test if something is valid or not in date range so I added some functions to tools.py.  Similar to ``is_current`` etc. in cpbuilder, but just tests two dates, but takes them in the format that they come from the db for convenience.
=> making date-range testing helper functions

news/TEMPLATE.rst, news/fix_path_in_tests.rst, regolith/builder.py, tests/test_broker.py, tests/test_builders.py
``test_round_trip`` now passes, but still some subprobcess errors on the builders that I am trying to hunt down.  This is stlil a WIP
=> trying to get tests to pass on windows

news/tweak_schema.rst, regolith/schemas.py, regolith/sorters.py
contacts is a lightweight people.  I thought of calling it collaborators, which is the main target, but I didn't want to restrict it to that.
=> schema updates for proposals and contacts

news/clean_people_schema.rst, regolith/schemas.py
These are the schema changes requested for people that will allow our public database to build without errors.
=> Clean people schema

news/clean_institutions_schema.rst, regolith/schemas.py
=> Little bit of schema cleaning in Institutions

news/fix_int_month_preslistbuilder.rst, regolith/builders/preslistbuilder.py, regolith/schemas.py
=> FIX: month to int now properly handled

news/csv_reader_for_columbia_classlist.rst, regolith/classlist.py
Right now it is for the version that comes from the Columbia Courseworks website, but it could be maybe made broader in application with a bit of thought.
=> adding a csv reader function for Columbia format classlists

news/editor_eye_fix.rst, regolith/builders/manuscriptreviewbuilder.py, tests/test_builders.py
do over of the manuscript builder fix with news and tests.  This should be ready for review and possible merge
=> redo fix for editor eye only and add tests and news

news/month_to_str.rst, regolith/dates.py, tests/test_dates.py
....but with leading zero's where necessary.
@scopatz this should be ready for review
=> adding helper functions because sometimes we want months as integer-like strings

news/fix_collections_imports.rst, regolith/runcontrol.py
@scopatz This should fix an out of date collections import in runcontrol.py
=> importing from collections.abc not collections

news/load_only_selected_dbs_again.rst, regolith/builders/cpbuilder.py, regolith/builders/cvbuilder.py, regolith/builders/gradebuilder.py, regolith/builders/postdocadbuilder.py, regolith/builders/preslistbuilder.py, regolith/builders/proposalreviewbuilder.py, regolith/builders/publistbuilder.py, regolith/builders/reimbursementbuilder.py, regolith/builders/resumebuilder.py, regolith/database.xsh, regolith/fsclient.py, regolith/interact.py, regolith/runcontrol.py, regolith/schemas.py, tests/test_builders.py, tests/test_runcontrol.py
@scopatz this should be ready for review and merge.  It completes the work that @CJ-Wright started to load only desired collections when they are local, to speed things up...
=> fix bug so only desired collections will open

news/grp_ids_to_tools..rst, regolith/builders/preslistbuilder.py, regolith/tools.py, tests/test_tools.py
This replaces #192 which will be closed.
@scopatz @CJ-Wright it is ready for review and merge
=> redo of move of group-members finder to tools

news/move_date_filters_dates.rst, regolith/dates.py, regolith/tools.py, requirements/run.txt, tests/test_dates.py
@scopatz this is a WIP.  Needs tests and all kinds of things.
=> Move all the date filters to the dates.py which may be a better place for them

requirements/run.txt
Hi, @sbillinge Could you merge this PR?
=> BLD: delete python in requirements

news/membershelper.rst, regolith/helper.py, regolith/helpers/l_membershelper.py, tests/test_helpers.py
=> List Group Members

regolith/helpers/l_membershelper.py, tests/test_helpers.py
=> made two lines for members

news/l_contactshelper.rst, regolith/helper.py, regolith/helpers/l_contactshelper.py, regolith/schemas.py, tests/test_helpers.py
=> Contact Lister

regolith/helpers/l_contactshelper.py, tests/test_helpers.py
=> Fixed contacts helper bug

news/finished_projecta.rst, regolith/helpers/l_projectahelper.py, regolith/schemas.py, tests/outputs/a_projectum/projecta.yaml, tests/test_helpers.py
=> WIP: Get finished projecta

news/str_date.rst, regolith/dates.py, tests/test_dates.py
=> Fix get_dates function

news/u_contacts.rst, regolith/helper.py, regolith/helpers/u_contacthelper.py, regolith/schemas.py, tests/outputs/u_contact/contacts.yaml, tests/test_helpers.py
Hi @sbillinge, can you please review my u_contact helper?
=> u_contact helper

regolith/commands.py, regolith/fsclient.py, regolith/main.py, regolith/mongoclient.py, requirements/run.txt, tests/test_commands.py
Add functionality: transfer the database from fielsystem to mongodb
=> WIP: filesystem to mongo

news/fix_u_contact.rst, news/u_contactfix.rst, regolith/helpers/u_contacthelper.py, tests/test_helpers.py
closes #444 and #443 
can you please review it?
I am trying to figure out why the error is happening with your empty list (issue 445). 
the problem seems to be linked to current, and not to notes though.
=> Contact helper issues

regolith/helper.py, regolith/helpers/u_milestonehelper.py, regolith/schemas.py, tests/outputs/a_projectum/projecta.yaml, tests/outputs/a_proposal/proposals.yaml, tests/outputs/u_milestone/projecta.yaml, tests/test_helpers.py, tests/u_milestone.rst
closes #406 
Can you please give a feedback to this helper?
=> WIP: milestone updater

news/u_milestone.rst, regolith/helpers/u_milestonehelper.py, tests/outputs/u_logurl/projecta.yaml, tests/outputs/u_milestone/projecta.yaml, tests/test_helpers.py
Can you please review it? 
closes #457
=> fixing due_date issue (u_milestone)

regolith/helpers/u_contacthelper.py, tests/test_helpers.py
I changed it, and now it retrieves a list and accepts either a fragment of the name or the id!
=> u_contact helper 

tests/test_tools.py
Last Friday, you asked me to pick some functions from tools.py and write some tests. 
=> added tests to tools

regolith/helpers/l_contactshelper.py, regolith/helpers/l_grantshelper.py, regolith/helpers/l_membershelper.py, regolith/helpers/l_milestoneshelper.py, regolith/helpers/l_projectahelper.py, regolith/tools.py, tests/test_helpers.py, tests/test_tools.py
=> WIP: Search Functionality

news/grp_by_lead.rst, regolith/helpers/l_projectahelper.py, tests/test_helpers.py
=> Added --grp_by_lead to l_projecta

news/search.rst
@sbillinge Here is the news for the search branch that was merged
=> Added news for search

regolith/helpers/u_milestonehelper.py, tests/test_helpers.py
Hi prof. @sbillinge !
I was doing tests and found a problem when there is no type in the milestone. 
This way, it will make sure that it gets None when type is not available. 
I tested it, and it worked.
=> fixed error with type (u_milestone)

regolith/helpers/a_expensehelper.py
@sbillinge I have accidentally deleted the database arg before it was merged, so I have re added the argument.
=> re added required database arg in a_expense

news/collect_appts.rst, regolith/tools.py, tests/test_tools.py
please see my collect appointments function (presently for use in grant burn function)!
=> collect appointments function

news/group_by_lead_expansion.rst, regolith/helpers/l_projectahelper.py, tests/test_helpers.py
=> Make group_by_lead work with other flags

regolith/helper.py, regolith/helpers/l_todohelper.py, regolith/schemas.py, tests/test_helpers.py
I tested several cases and all passed.  If the basic function of l_todo can be settled as this, maybe we could merge l_todo first, then add a_todo, f_todo... one by one?
=> first version of l_todo helper

regolith/helpers/u_milestonehelper.py, tests/outputs/u_logurl/projecta.yaml, tests/outputs/u_milestone/projecta.yaml, tests/test_helpers.py
Hi @sbillinge !
Now, when the user informs only "20dy" (for example), it returns all the projectum ids that contain "20dy"! 
Also, when verbose is not informed, it returns a simple list, with the name of the milestone, due date and status!
=> changes to u_milestone.py

docs/broker.rst
broker.rst Updated with more explicit detail.
=> broker.rst Updated

news/finish_prum.rst, regolith/helper.py, regolith/helpers/u_finishprumhelper.py, tests/outputs/finish_prum/projecta.yaml, tests/test_helpers.py
Hi, prof. @sbillinge,
I added the tests to the finish_prum, can you please take a look?
=>  finish_prum helper

news/kv_filter_expansion.rst, regolith/helpers/l_contactshelper.py, regolith/helpers/l_grantshelper.py, regolith/helpers/l_membershelper.py, regolith/helpers/l_milestoneshelper.py, regolith/helpers/l_projectahelper.py, tests/test_helpers.py
=> kv_filter expansion

news/u_institutions.rst, regolith/helper.py, regolith/helpers/u_institutionshelper.py, regolith/schemas.py, tests/outputs/u_institutions/institutions.yaml, tests/test_helpers.py
Closes #423 
Hi professor @sbillinge,
Can you review my initial tests?
=> u_institution

regolith/helper.py, regolith/helpers/u_institutionshelper.py, tests/test_helpers.py
Hi @sbillinge!
It should work properly now! It was only retrieving by id, and now I added aka and name. 
Also, do you think a verbose could be useful? I can try to add it if you wish!
=> modified fragment retrieval  and changed to u_institution

regolith/helpers/l_projectahelper.py, tests/test_helpers.py
=> WIP: Cleaning up l_projecta

news/get_dates_prefix.rst, regolith/dates.py, tests/test_dates.py
=> Add prefix string argument to get_dates

news/l_projecta_verbose.rst, regolith/helpers/l_projectahelper.py, tests/test_helpers.py
=> l_projecta -v flag now prints verbosely

regolith/helpers/l_contactshelper.py, tests/test_helpers.py
=> Added verbose to l_contacts

news/a_todo.rst, news/l_todo.rst, regolith/helper.py, regolith/helpers/a_todohelper.py, regolith/helpers/l_todohelper.py, tests/outputs/a_todo/people.yaml, tests/test_helpers.py
Hi @sbillinge, I create this new PR in order not to rebase.
=> Todo adder ready to be merged

regolith/helpers/u_contacthelper.py, tests/test_helpers.py
Hi @sbillinge,
I made changes, but I am still unsure of what I should do with email. 
I don't really see how the email validator should behave, especially bc it is called even when there is no email (and it is an optional field). Also, it does not seem practical to have email url, cred, etc., specified in the command line when adding a new email. I guess it should be good to have a validator to an email address, but maybe we should move them somewhere else?
=> u_contact issue 524

regolith/helpers/l_contactshelper.py, tests/test_helpers.py
Closes #530 
@sbillinge ready for review and merge!
=> changed format of output l_contacts

regolith/helpers/makeappointmentshelper.py, tests/test_helpers.py
made a `run` required argument for the `makeappointments` helper to work as in `l_contacts` after noticing a bug while trying it in my local!
=> makeappointments run bug

news/mdyfunction.rst, regolith/builders/coabuilder.py, regolith/builders/reimbursementbuilder.py, regolith/dates.py, tests/test_dates.py
Closes #514 
Hi prof. @sbillinge,
I moved the mdy function from reimb builder to dates and added tests.
=> deleted mdy function from reimb builder

regolith/helpers/u_milestonehelper.py
Closes #544 
a_projectum does insert a type by default!
@sbillinge can you please review it?
=> Changed message for type in u_milestone

regolith/helpers/l_contactshelper.py, tests/test_helpers.py
Closes #536 
Hi @sbillinge!
I made changes to the l_contacts. My changes were mostly done to the function stringify, which I am not sure if it is optimal. However, to make it differently, I think I would need to make big changes to the structure of the helper, because right now it is using this function to get all the data and transform to a string, so I would have to change it back to a dictionary to work on it. 
Please let me know what your thoughts are on this! I would be happy to make it differently if you wish!
=> changed output (regular and verbose) l_contacts

news/webinar_presentations.rst, news/webinar_type_allowed.rst, regolith/builders/preslistbuilder.py, regolith/schemas.py, regolith/templates/preslist.tex, tests/outputs/preslist/presentations-ergs-scopatz.tex
Closes #456 
Hi @sbillinge!
Can you please review and merge this?
=> added webinar as an allowed type to presentations

regolith/dates.py, tests/test_dates.py
=> Fix get_dates

regolith/schemas.py
I retrieved with keyword "date" in schemas, and found three of them that needed to be modified.
=> add date type in schemas

news/meeting_validator.rst, regolith/helper.py, regolith/helpers/v_meetingshelper.py, regolith/tools.py, tests/test_helpers.py, tests/test_tools.py
=> WIP: Meeting Validator

regolith/helpers/makeappointmentshelper.py, tests/test_helpers.py
to solve problem of tests hanging until Matplotlib windows are closed!
=> suppress GUI in tests for makeappointments helper

regolith/helpers/u_finishprumhelper.py, tests/outputs/finish_prum/projecta.yaml
Closes #552
Hi @sbillinge,
Can you please review and merge?
=> made prum finisher insert date not string

regolith/schemas.py
@sbillinge , please review and merge.
=> amount type from int to float

regolith/helpers/a_todohelper.py, regolith/helpers/f_todohelper.py, regolith/helpers/l_todohelper.py, regolith/helpers/u_todohelper.py, regolith/schemas.py, regolith/tools.py, tests/outputs/a_todo/people.yaml, tests/outputs/f_todo/people.yaml, tests/outputs/u_todo/people.yaml, tests/test_helpers.py
@sbillinge Hi Simon! Please check the new feature. 
Now in u_todo and f_todo, user can update tasks from all databases by entering running_index.
=> add running_index

regolith/helpers/u_milestonehelper.py
Closes #571 
Hi prof. @sbillinge !
Ahmed asked me to add 'cancelled' as an allowed status for u_milestones. I choose the letter 'd', because 'c' is already used to converged. If the letter choice is ok, can you please merge it?
=> added cancelled as an allowed status

regolith/helpers/f_todohelper.py, regolith/helpers/l_todohelper.py, regolith/helpers/u_todohelper.py
=> improve sorting in todolist

regolith/builders/htmlbuilder.py, tests/outputs/a_manurev/refereeReports.yaml
Hi Prof. @sbillinge!
Here is the pull request with the changes we talked about today.
=> HTML Builder - changed function finish, adding a if statement

regolith/helpers/l_projectahelper.py, tests/test_helpers.py
@sbillinge 
--all, --current, and --ended (with -d, -r, and standalone) all work now...at least locally.
=> fixed --all, --ended, and --current

news/enh_beamplan.rst, regolith/builders/beamplanbuilder.py, regolith/schemas.py, regolith/templates/beamplan.tex, regolith/templates/beamplan.txt, tests/outputs/beamplan/2020-1-XPD.tex, tests/outputs/beamplan/2020-1-XPD.txt, tests/outputs/beamplan/2020-1-XPDNotes.bib, tests/test_builders.py
Improve the beamplan builders:
* Beamplanbuilder includes the scan plan code in the report.
* Scanplan schemas changes from string to list of strings.
* Sample information is demonstrated in a list instead of a comma separated line.
=> ENH: beamplanbuilder

tests/outputs/a_manurev/refereeReports.yaml, tests/test_helpers.py
=> fixed ma and proprev tests

news/news0.rst, regolith/schemas.py, tests/outputs/internalhtml/grpmeetings.html, tests/outputs/internalhtml/intindex.html, tests/test_builders.py
@sbillinge updated the exemplar in schemas for the "meetings" using the meeting on 07-31 from meetings.yml
=> WIP: InternalHtml Schemas and Outputs

regolith/helpers/a_projectumhelper.py
@sbillinge , sorry I think I forget to push this commit while you merge the PR before.
This PR also includes your fix on the `action='store_true',`, so I think only merging this PR would be enough.
=> Checklist builder

regolith/helpers/a_projectumhelper.py
Reverts regro/regolith#648
Going back to the old checklist again per discussion in weekly chat
=> Revert "WIP: update projectum checklist builder"

news/sm_reading_lists.rst, regolith/builder.py, regolith/builders/readinglistsbuilder.py, regolith/templates/rlistbibfile.bib, regolith/templates/rlistbibfile.txt, regolith/tools.py, requirements/run.txt, tests/test_builders.py
=> WIP: reading list builder

regolith/builders/gradebuilder.py
@scopatz this is another WIP.  I wanted gradebuilder to print an ordered summary of the grades.  I will work to clean this a bit so no need to review right now.
=> WIP: add a summary print statement

news/review_schemas.rst, regolith/builders/proposalreviewbuilder.py, regolith/schemas.py, regolith/templates/propreport.txt, tests/outputs/review-man/1902nature_sbillinge_author.txt, tests/outputs/review-man/1902nature_sbillinge_editor.txt, tests/outputs/review-prop/1906doeExample_sbillinge.txt, tests/outputs/review-prop/1906nsfExample_sbillinge.txt, tests/test_builders.py
squashing last couple of bugs, this time to the code, for the schema … update to proposal review builder
This is still a WIP until I build the tests and make them pass
=> WIP: add testing to proposal review builder and squash last few bugs from schema change

regolith/schemas.py
Regarding spaces : result of a ' ctrl+alt+L ' in pycharm - did not changed content
=> request to fix' files' (see '+1: Yevgeny') + fixing spaces 

news/filter_recursive.rst, regolith/tools.py, tests/test_tools.py
=> Make the --filter flag search recursively and added testing

news/updateSchema.rst, regolith/schemas.py, tests/outputs/a_expense/expenses.yaml, tests/outputs/a_projectum/projecta.yaml, tests/outputs/finish_prum/projecta.yaml, tests/outputs/u_logurl/projecta.yaml, tests/outputs/u_milestone/projecta.yaml
Two tests failed: test_builders and test_commands. I don't remember how to fix these types of errors.
=> migrated the schemas from group/local/regolithrc

tests/test_commands.py
fix implemented, committing to see if it works on linux/mac
=> test_fs_to_mon_fix_on_win

docs/commands/fs-to-mongo.rst, docs/commands/index.rst, docs/rc.rst, news/MultiClient.rst, regolith/client_manager.py, regolith/database.xsh, regolith/main.py, regolith/mongoclient.py, regolith/runcontrol.py, tests/conftest.py, tests/test_client_manager.py, tests/test_commands.py
Added a client wrapper class to allow for clients across different databases. Tested manually rather than implementing a new conftest fixture. Next step is potentially to implement an additional conftest fixture and to create an interface metaclass for the clients to inherit from, requiring that client classes have specific methods with specific arguments.
=> Multi client

news/TEMPLATE.rst, regolith/fsclient.py, regolith/helper_gui_main.py, regolith/helpers/a_expensehelper.py, regolith/helpers/a_grppub_readlisthelper.py, regolith/helpers/a_manurevhelper.py, regolith/helpers/a_presentationhelper.py, regolith/helpers/a_projectumhelper.py, regolith/helpers/a_proposalhelper.py, regolith/helpers/a_proprevhelper.py, regolith/helpers/a_todohelper.py, regolith/helpers/f_todohelper.py, regolith/helpers/l_abstracthelper.py, regolith/helpers/l_contactshelper.py, regolith/helpers/l_grantshelper.py, regolith/helpers/l_milestoneshelper.py, regolith/helpers/l_progressreporthelper.py, regolith/helpers/l_projectahelper.py, regolith/helpers/l_todohelper.py, regolith/helpers/makeappointmentshelper.py, regolith/helpers/u_contacthelper.py, regolith/helpers/u_finishprumhelper.py, regolith/helpers/u_institutionshelper.py, regolith/helpers/u_logurlhelper.py, regolith/helpers/u_milestonehelper.py, regolith/helpers/u_todohelper.py, requirements/run.txt, scripts/helper_gui, scripts/helper_gui.bat, setup.py
I added more widgets and edited some text to make the GUI look prettier. I didn't know what to do with the "run" arguments under l_contacts and makeappointments. One thing to note is that running regolith helper from cmd will no longer work when I add widgets to the helpers, so I'm thinking that maybe we should have two seperate folders. The first folder will house the original helper files that regolith helper uses, and the second one will have the modified helper files that are imported into the helper_gui_main.py file.
=> Cleaning up the GUI and adding more widgets to helpers

regolith/helpers/a_expensehelper.py, regolith/helpers/a_grppub_readlisthelper.py, regolith/helpers/a_manurevhelper.py, regolith/helpers/a_presentationhelper.py, regolith/helpers/a_projectumhelper.py, regolith/helpers/a_proposalhelper.py, regolith/helpers/a_proprevhelper.py, regolith/helpers/a_todohelper.py, regolith/helpers/f_todohelper.py, regolith/helpers/l_abstracthelper.py, regolith/helpers/l_contactshelper.py, regolith/helpers/l_grantshelper.py, regolith/helpers/l_milestoneshelper.py, regolith/helpers/l_progressreporthelper.py, regolith/helpers/l_projectahelper.py, regolith/helpers/l_todohelper.py, regolith/helpers/makeappointmentshelper.py, regolith/helpers/u_contacthelper.py, regolith/helpers/u_finishprumhelper.py, regolith/helpers/u_institutionshelper.py, regolith/helpers/u_milestonehelper.py, regolith/helpers/u_todohelper.py
I made the code better by using isinstance() and **kwargs. Helpers should be able to run from both the command line and via the gui now. I am making this PR via the github website, but I still don't know why the CI isn't triggering. The weird thing is that the CI triggers for my PRs on to rg-db-group.
=> Branch off of original gooey branch

regolith/helpers/a_proposalhelper.py, regolith/helpers/l_abstracthelper.py, regolith/helpers/l_todohelper.py, regolith/helpers/u_milestonehelper.py
I made a new branch off of gooey before the rebase. I fixed all the bugs on this branch, and all my tests are passing locally. Hopefully everything works out now.
=> Fixing all the bugs on a new branch off of gooey

news/mongo_to_fs.rst, regolith/mongoclient.py
I also inserted code such that the existing subprocess calls print what went wrong before providing a traceback, which should be outstandingly useful for any future issues
=> Fixed mongo to fs

regolith/helpers/l_abstracthelper.py
I edited the code so that, if l_abstract passes a --loc_inst to a presentation that has both 'location' and 'institution', then location will take priority. If a presentation only has 'institution', then the program will only lists presentations that are seminars/ colliquims
=> Fixes issue #696

regolith/helpers/a_projectumhelper.py, regolith/helpers/u_milestonehelper.py, tests/outputs/a_projectum/projecta.yaml, tests/outputs/u_logurl/projecta.yaml, tests/outputs/u_milestone/projecta.yaml, tests/test_helpers.py
=> Updating a_projectum to have a --notes field

docs/helper_gui.rst
I replaced 'tree' with 'blob' in the urls. Hopefully this gets images to show in the helper_gui.rst
=> Updating image urls to get images to show in helper_gui.rst

regolith/database.xsh
=> Revised a typo the recent edit to database.xsh

regolith/helper.py, regolith/helpers/attestationshelper.py, regolith/schemas.py, tests/outputs/a_expense/expenses.yaml, tests/outputs/a_presentation/expenses.yaml, tests/test_helpers.py
=> Helperizing attestations, closes #827

regolith/helpers/l_abstracthelper.py, tests/test_helpers.py
=> Switched l_abstract filter from OR logic to AND

regolith/helper.py, regolith/helpers/reimbstatushelper.py, regolith/schemas.py, tests/outputs/a_expense/expenses.yaml, tests/outputs/a_presentation/expenses.yaml, tests/test_helpers.py
=> Helper and test for reimbstatushelper

CHANGELOG.rst, regolith/__init__.py, rever.xsh, setup.py
Series of commits to unwind previously made commits with undesired changes while still preserving integrity of the repo history
=> Cbracy revert regolith to v0.6.0

news/version.rst, regolith/main.py, tests/test_main.py
added function "regolith --version" to print version number of regolith. This is to address PR #819
=> DEV: add function version

news/inst_error_patch.rst, regolith/builders/coabuilder.py, regolith/schemas.py, regolith/templates/person.html, regolith/tools.py, tests/outputs/html/people/scopatz.html, tests/test_tools.py
=> better error message for missing inst

news/pres_url.rst, regolith/helpers/a_presentationhelper.py, regolith/schemas.py, tests/outputs/a_presentation/presentations.yaml, tests/test_helpers.py
=> ENH: adding presentation url to presentation in presentations

tests/test_validate.py
=> patch calledProcessError in test_validate

news/u_milestone_finish.rst, regolith/helpers/u_milestonehelper.py
=> Fix issue #914

regolith/helpers/u_milestonehelper.py, regolith/schemas.py, tests/outputs/a_projectum/projecta.yaml, tests/outputs/f_prum/projecta.yaml, tests/outputs/u_logurl/projecta.yaml, tests/outputs/u_milestone/projecta.yaml
=> adding type to schema for kickoff meeting

news/u_milestone_uuid_new.rst, regolith/helpers/u_milestonehelper.py, tests/outputs/f_prum/projecta.yaml, tests/outputs/u_logurl/projecta.yaml, tests/outputs/u_milestone/projecta.yaml, tests/test_helpers.py
=> U milestone UUID new

news/patch_read_list_updater.rst, regolith/builders/readinglistsbuilder.py, regolith/helpers/a_grppub_readlisthelper.py, tests/outputs/a_grppub_readlist/reading_lists.yaml, tests/test_helpers.py
to make it more readable and to remove duplicates
=> refactored adder for making reading lists from tags

news/cmds_to_cmds.rst, regolith/commands.py, regolith/helper_gui_main.py, regolith/main.py, regolith/schemas.py
- moving commands dict to commands.py as it is used in multiple places
- news
=> cmds to cmds

regolith/helpers/a_projectumhelper.py, regolith/helpers/u_milestonehelper.py
I left three E501 issue on url string, it might be fixed on next PR.
=> Fix most E501 F451 issue on u_milestonehelper and a_projectumhelper

.gitattributes, .github/workflows/docs.yml, .github/workflows/main.yml, .github/workflows/pre-commit.yml, .isort.cfg
=> untrack hidden files

src/regolith/builders/basebuilder.py, src/regolith/builders/coabuilder.py, src/regolith/builders/cpbuilder.py, src/regolith/builders/grantreportbuilder.py, src/regolith/builders/preslistbuilder.py, src/regolith/builders/publistbuilder.py, src/regolith/helpers/a_todohelper.py, src/regolith/helpers/attestationshelper.py, src/regolith/helpers/basehelper.py, src/regolith/helpers/l_abstracthelper.py, src/regolith/helpers/l_contactshelper.py, src/regolith/helpers/l_currentappointmentshelper.py, src/regolith/helpers/l_generalhelper.py, src/regolith/helpers/l_milestoneshelper.py, src/regolith/helpers/l_projectahelper.py
=> pre-commit files in src/regolith dir

CHANGELOG.rst, requirements/test.txt
=> Change requirements/test.txt and add CHANGLOG.rst

doc/source/conf.py, doc/source/index.rst, src/regolith/schemas.json
Merge these files. I think now it is ready for release check as I have checked all the html documentation
=> update conf.py, update link in doc/source/index.rst, and update schemas.json

src/regolith/builders/basebuilder.py, src/regolith/database.xsh, src/regolith/deploy.py, src/regolith/helpers/basehelper.py, src/regolith/storage.py, src/regolith/tests/bootstrap_builders.py, src/regolith/tests/conftest.py, src/regolith/tests/test_validate.py
=> deprecation remove

doc/source/index.rst
mostly copied over from the old version -- hopefully didn't miss anything!
=> cookierelease: copied over index.rst

pyproject.toml
fix #1177 (add pip.txt to pyproject toml so we can now run pip install -e . )
=> add pip to pyproject.toml

.pre-commit-config.yaml, pyproject.toml, src/regolith/tests/outputs/grant-report/SymPy-1.1_report_2017-04-01_2018-03-31.txt, src/regolith/tests/outputs/review-prop/1906nsfExample_sbillinge.txt
fix #1186 
- remove duplicate lines in pyproject.toml
- (pre-commit) ignore txt files when trimming whitespaces 
- restore old version of txt files so pytest is passing
=> Cookie: restore old txt files (so pytest is passing)

.github/workflows/tests-on-pr.yml, requirements/conda.txt, src/regolith/exemplars.json, src/regolith/schemas.py
remove some warnings and at the same time test the ci
=> change position values in grants to remove warnings in tests

src/regolith/helpers/makeappointmentshelper.py
=> fix matplotlib plot_date warnings

.github/workflows/tests-on-pr.yml
Closes https://github.com/regro/regolith/issues/1196
=> Remove `cookie` branch in tests on pr

news/prumtweaks.rst, src/regolith/helpers/a_projectumhelper.py, src/regolith/helpers/u_milestonehelper.py, tests/outputs/a_projectum/projecta.yaml, tests/outputs/f_prum/projecta.yaml, tests/outputs/u_logurl/projecta.yaml, tests/outputs/u_milestone/projecta.yaml
=> style: change how prums and milestones are added so there is less bloat
